on:
  push:
    branches:
      - "main"

env:
  NODE_VERSION: '12.x'     

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: install and deploy 
      run: |
        git config --global user.name 'Rogier de Ruijter'
        
        # git config --global user.email 'your-username@users.noreply.github.com'
        git config --global user.email 'rogierderuijter@hotmail.com'
        
        # Install, build and 
        yarn install
        # npm test (Add this in when there are tests)
        yarn deploy
